"""add submission idempotency key

Revision ID: 4a1e5dbc1e1c
Revises: 47aad2a88f1c
Create Date: 2026-09-05 15:35:56.636369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1e5dbc1e1c'
down_revision: Union[str, Sequence[str], None] = '47aad2a88f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index('uq_submission_tenant_widget_idempotency', 'submissions', ['tenant_id', 'widget_id', 'idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_submission_tenant_widget_idempotency', table_name='submissions')
    op.drop_column('submissions', 'idempotency_key')
    # ### end Alembic commands ###
